version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=farm
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=test
    ports:
      - "3310:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8777:8080"
